name: Review Workflow

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, ready_for_review]
    branches-ignore:
      - main
      - dev
      - staging
      - release/**
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Check if comment contains /review
        if: github.event_name == 'issue_comment'
        run: |
          if [[ ! "${{ github.event.comment.body }}" =~ /review ]]; then
            echo "Comment does not contain /review command. Stopping workflow."
            exit 1
          fi

      - name: Check if comment is on a PR
        if: github.event_name == 'issue_comment'
        run: |
          if [[ -z "${{ github.event.issue.pull_request }}" ]]; then
            echo "Comment is not on a pull request. Stopping workflow."
            exit 1
          fi

      - name: Check if PR is not draft
        if: github.event_name == 'pull_request'
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
            echo "PR is still in draft. Stopping workflow."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request?.number || 
                           context.payload.issue?.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: '✅ Review process completed!'
            });

      - name: Run your review logic
        run: |
          echo "Running review process..."
          # Add your review commands here
