name: Test Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: contains(github.event.comment.body, '/test') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Test response
        run: echo "Comment trigger works!"
